package npc

import chisel3._
import chisel3.util._

class ysyx_23060336_AXI4Slave extends Bundle{
    val awready = Output(Bool())
    val awvalid = Input(Bool()) 
    val awaddr  = Input(UInt(Base.addrWidth.W)) 
    val awid    = Input(UInt(Base.idWidth.W)) 
    val awlen   = Input(UInt(Base.lenWidth.W)) 
    val awsize  = Input(UInt(Base.sizeWidth.W)) 
    val awburst = Input(UInt(Base.burstWidth.W)) 
    val wready  = Output(Bool())
    val wvalid  = Input(Bool()) 
    val wdata   = Input(UInt(Base.dataWidth.W)) 
    val wstrb   = Input(UInt(Base.wstrbWidth.W)) 
    val wlast   = Input(Bool()) 
    val bready  = Input(Bool()) 
    val bvalid  = Output(Bool())
    val bresp   = Output(UInt(Base.respWidth.W))
    val bid     = Output(UInt(Base.idWidth.W))
    val arready = Output(Bool())
    val arvalid = Input(Bool()) 
    val araddr  = Input(UInt(Base.addrWidth.W)) 
    val arid    = Input(UInt(Base.idWidth.W)) 
    val arlen   = Input(UInt(Base.lenWidth.W)) 
    val arsize  = Input(UInt(Base.sizeWidth.W)) 
    val arburst = Input(UInt(Base.burstWidth.W)) 
    val rready  = Input(Bool()) 
    val rvalid  = Output(Bool())
    val rresp   = Output(UInt(Base.respWidth.W))
    val rdata   = Output(UInt(Base.dataWidth.W))
    val rid     = Output(UInt(Base.idWidth.W))
    val rlast   = Output(Bool())
}

class ysyx_23060336_AXI4Master extends Bundle{
    val awready = Input(Bool())
    val awvalid = Output(Bool()) 
    val awaddr  = Output(UInt(Base.addrWidth.W)) 
    val awid    = Output(UInt(Base.idWidth.W)) 
    val awlen   = Output(UInt(Base.lenWidth.W)) 
    val awsize  = Output(UInt(Base.sizeWidth.W)) 
    val awburst = Output(UInt(Base.burstWidth.W)) 
    val wready  = Input(Bool())
    val wvalid  = Output(Bool()) 
    val wdata   = Output(UInt(Base.dataWidth.W)) 
    val wstrb   = Output(UInt(Base.wstrbWidth.W)) 
    val wlast   = Output(Bool()) 
    val bready  = Output(Bool()) 
    val bvalid  = Input(Bool())
    val bresp   = Input(UInt(Base.respWidth.W))
    val bid     = Input(UInt(Base.idWidth.W))
    val arready = Input(Bool())
    val arvalid = Output(Bool()) 
    val araddr  = Output(UInt(Base.addrWidth.W)) 
    val arid    = Output(UInt(Base.idWidth.W)) 
    val arlen   = Output(UInt(Base.lenWidth.W)) 
    val arsize  = Output(UInt(Base.sizeWidth.W)) 
    val arburst = Output(UInt(Base.burstWidth.W)) 
    val rready  = Output(Bool()) 
    val rvalid  = Input(Bool())
    val rresp   = Input(UInt(Base.respWidth.W))
    val rdata   = Input(UInt(Base.dataWidth.W))
    val rlast   = Input(Bool())
    val rid     = Input(UInt(Base.idWidth.W))
}
